### ISSUE TITLE
默认头像显示为。

### ISSUE THREAD

**Issue by asing** [vieasehub/viease#13]
用户的头像为微信默认头像时候，在viease后台显示为。是bug吗？

**Comment by overtrue** [comment]
截图看看吧

**Comment by asing** [comment]
![qq 20160321141756](https://cloud.githubusercontent.com/assets/345259/13911783/d927621a-ef6f-11e5-94f5-db88b5e94fad.png)

**Comment by overtrue** [comment]
没有头像，连昵称都没有？

**Comment by asing** [comment]
昵称不确定，有的有昵称，有的没有，我截图了。没头像的是 viease，有头像的是微信公众号后台。
<img width="286" alt="2016-03-21 15 41 33" src="https://cloud.githubusercontent.com/assets/345259/13912777/810d81ca-ef7b-11e5-9f1f-a837bd09e9ac.png">
<img width="217" alt="2016-03-21 15 41 45" src="https://cloud.githubusercontent.com/assets/345259/13912778/8110fbe8-ef7b-11e5-9824-b7c868a4fc0d.png">


个人判断是否有2个因素
1.用户已取消关注
2.用户昵称中有 emoji 表情？

**Comment by overtrue** [comment]
@asing 

1. 头像的问题你看看改一下代码，然后提交一个PR，我这里给你合并
2. 昵称，你的数据库字符集要是 utf8mb4

**Comment by asing** [comment]
ok
