### ISSUE TITLE
docker 容器不应该包含 sshd

### ISSUE THREAD

**Issue by stenote** [vieasehub/viease#15]
**docker** 容器不应该包含 **sshd**

应考虑使用 `docker exec -it` 等命令进入到容器中

**Comment by stenote** [comment]
repost again .

**Comment by stenote** [comment]
@overtrue

**Comment by overtrue** [comment]
@Lee2011

**Comment by Lee2011** [comment]
@stenote @overtrue 这个Docker容器只是为了方便搭建开发环境而做的一个类似于 Homestead 的容器，不适用于生产环境的部署。参考：[shincoder/homestead-docker](https://github.com/shincoder/homestead-docker)

如果用于正式部署，可以参考[docker-for-the-laravel-framework](http://dylanlindgren.com/docker-for-the-laravel-framework/)，将 data volumn，phpfpm 和 nginx 分别放在不同的容器中，然后用 docker compose 将他们 link 起来。

**Comment by stenote** [comment]
@Lee2011 roger that~
