### ISSUE TITLE
能放在SAE上面吗？

### ISSUE THREAD

**Issue by yumemor** [vieasehub/viease#17]
看了感觉很不错，很想使用啊 支持SAE吗？ 其它的云引擎也可以

**Comment by overtrue** [comment]
@yumemor 不支持，很多云引擎禁用了文件系统函数。

**Comment by callmesoul** [comment]
现在sae不是出了个云空间么？好像是和其他云服务器一样的，虽然要收钱，但是比较便宜，8块钱一个月。用这个应该是行的

**Comment by overtrue** [comment]
@callmesoul 那应该没问题

**Comment by yumemor** [comment]
@callmesoul 你说的是云主机？不是8元吧 还是云豆 云容器和SAE的云引擎融合了

**Comment by yumemor** [comment]
@overtrue 世界真是小啊，在这遇见你了 请问这是你的博客吗？overtrue.me 我想问下这个博客的原创主题是你吗？ 我这里写了一个基于这个移植过来的hexo主题 好像一直是jekyll的主题  一直不知道原创作者是谁 能告诉我吗？ 我的README一直没写原作者 很惭愧啊！

**Comment by callmesoul** [comment]
@yumemor 云空间！！！

**Comment by yumemor** [comment]
![image](http://ww3.sinaimg.cn/large/006clTSSgw1f2slivr5eyj304408f0sy.jpg)

**Comment by yumemor** [comment]
@callmesoul ![image](http://ww3.sinaimg.cn/large/006clTSSgw1f2slivr5eyj304408f0sy.jpg)

**Comment by callmesoul** [comment]
@yumemor  http://mp.weixin.qq.com/s?__biz=MjM5NzI0Njc2MA==&mid=415856613&idx=1&sn=47ef7f9c09dc2e3dd58a64c3240fae6c&scene=1&srcid=0401YHJoQ8o3kZAbUjugAsn1#wechat_redirect

**Comment by yumemor** [comment]
@callmesoul  感觉被打脸了，， 原来这是云空间啊 谢谢告知！我还一直不知道这东西。

**Comment by overtrue** [comment]
@yumemor 哈哈，是我。overtrue.me是我的博客，然后源码在这里：https://github.com/overtrue/overtrue.github.io 可以随意 使用。:smile:

**Comment by callmesoul** [comment]
@yumemor  一登陆sae就会自动弹出提示新出了云空间，你自己没看

**Comment by yumemor** [comment]
@callmesoul 还以为是广告什么的，直接关闭

**Comment by yumemor** [comment]
@overtrue 嗯，好的 总算找到了原作者
