### ISSUE TITLE
关于requirejs加载路径问题

### ISSUE THREAD

**Issue by wh469012917** [vieasehub/viease#18]
我在自己的一个项目中参考了你vieasy的requirejs使用，但是碰到了这样的一个问题：
在入口的main.js的paths中配置好jquery的路径，比如这样子：
```js
requirejs.config({
	baseUrl : "/js",
	paths : {
		"jquery" : "plugins/jQuery/jquery-1.12.3.min",
	}
	}
});
```
目录结构是这样：
```
|----/
    |----js
        |----plugins
        |----pages
            |----page1.js
            |----page2.js
        |----main.js
        |----require.js
    |----css
    |----img
```
在`page1.js`中这样子写代码：
```js
define(['jquery'],function($){
	$(function(){
                //TODO
	});
});
```
然后在需要的地方这样去引用：
```
require(['pages/page1']);
```
这样在配置文件中配置好jquery的路径后，但是这样子会在**随机情况下**出现不会到配置好的路径下去加载jquery，而是加载`/js/jquery.js`，这样就会出现404的情况，但是大部分时候还是好的。
这个问题困扰我很久了，网上查了资料基本上都是抄来抄去，如果你能有一些解决思路，在方便的时候麻烦回复下，谢谢了。

**Comment by wh469012917** [comment]
我目前的一个解决方案是`main.js`不要拿到`data-main`这里加载，而是新建一个`script`标签来加载，这样就不会出现这样子的问题，但还是想知道原因。

**Comment by overtrue** [comment]
@wh469012917 我也不是太熟悉这个东西，我之前用的时候也经常出问题，文件加载顺序问题。已经好久不用require js了

**Comment by wh469012917** [comment]
@overtrue 嗯，没事，谢谢。那有没有啥好的类似东西呢？seajs用过吗

**Comment by overtrue** [comment]
@wh469012917 现在用gulp, webpack 这样的东西来打包处理了。

**Comment by wh469012917** [comment]
@overtrue ok，Thinkyou！

**Comment by overtrue** [comment]
@wh469012917 不客气 。
