### ISSUE TITLE
公众账号设置如何URL(服务器地址)

### ISSUE THREAD

**Issue by zhouhao4221** [vieasehub/viease#19]
我看了路由列表但是没有找到关于消息接收方面的。
还有自动回复的数据是保存不了吗，js里面没有缺少ajax的代码
`
//19行 ：/js/admin/pages/reply.js  
    // 保存添加  

    $(document).on('submit', '.form-create', function(event){  
        event.preventDefault();  
        var $rule = Util.parseForm($('.form-create'));  
        console.log($rule);  
        // 保存  
    });  
`

**Comment by overtrue** [comment]
@zhouhao4221 请阅读 README 第一段，谢谢
