### ISSUE TITLE
homestead 0.4.1 box

### ISSUE THREAD

**Issue by huanghua581** [vieasehub/viease#8]
默认没有 mcrypt

执行以下命令，更新系统：

`sudo apt-get update       &&
sudo apt-get install mcrypt php7.0-mcrypt       &&
sudo apt-get upgrade`

可以备注一下

**Comment by overtrue** [comment]
@huanghua581 感谢，么么哒 :kiss:

**Comment by huanghua581** [comment]
@overtrue 么么哒
